# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5630f1e2aff75bdcc61cbfb2d7abc4f6d1f7c80142fa2a21ee7a79cdeae91d10b4b47c9b6a2ec0675a62ab64c28770f1d471cb3efa2ead5d5093e24a63434cad

test:
  secret_key_base: e56499c5151fa6e4c06d97ffc1f4adcd1b1b9e4cf0bd4e0a114ced2f2b45117b2709fdd32666278bad2fa5bbe4160cedb5db825d131358c91a4a3b44abc3a3c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
